### ISSUE TITLE
Can't locate object method "await" via package "JavaScript::QuickJS::Promise"

### ISSUE THREAD

**Issue by gryphonshafer** [FGasper/p5-JavaScript-QuickJS#10]
The following works under JavaScript::QuickJS::Promise version 0.19 but fails under version 0.20:

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use JavaScript::QuickJS;

my $js = JavaScript::QuickJS
    ->new
    ->eval_module( q<
        export default function (input) {
            return input;
        }
    > )->await;
```

The error message returned is:

    Can't locate object method "await" via package "JavaScript::QuickJS::Promise"

**Comment by gryphonshafer** [comment]
Sorry, I may have confused myself. This behavior may be by design. Should the final `await` just be called off the object instantiated object from `new`?

**Comment by FGasper** [comment]
@gryphonshafer Oops.

`eval_module()` used to return the $js object because QuickJS didn’t return anything useful (in C, that is) in module mode. That’s changed now, though: now `eval_module()` returns a promise. This is actually what drove the creation of the new Promise wrapper.

I should have noted this change as a breaking one in the changelog. I’ll make that change retroactively.

**Comment by FGasper** [comment]
But yes, this is intended functionality. Call $js->await(), not $promise->await().

**Comment by gryphonshafer** [comment]
OK, cool. Does `Quick::JS->await` wait for all promises from the instantiated object to complete, or does one need to check all the promises directly?

**Comment by FGasper** [comment]
await() should block until all pending work (e.g., promises) completes. It’s just a wrapper around QuickJS, though, so whatever QuickJS does is what you get.

**Comment by gryphonshafer** [comment]
Fantastic. I love your module. Thank you.
